import { useState } from 'react';
import { Card, CardContent, CardHeader } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Textarea } from '../components/ui/textarea';
import { Badge } from '../components/ui/badge';
import { ArrowLeft, Brain, Loader2, Download, Share2, Save } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { callSemSenseAI } from '../config/api';

interface Subject {
  name: string;
  credits: number;
  difficulty: 'Easy' | 'Medium' | 'Hard';
}

interface AnalysisResult {
  success: boolean;
  data: {
    semesterNumber: number;
    studentName: string;
    analysisTimestamp: string;
    aiAnalysis: string;
    subjectsCount: number;
    weeklyAvailableHours: number;
  };
}

export function SemSenseAI() {
  const navigate = useNavigate();
  const { userProfile } = useAuth();
  const [step, setStep] = useState<'form' | 'analysis'>('form');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [analysisResult, setAnalysisResult] = useState<AnalysisResult | null>(null);

  // Form state
  const [semester, setSemester] = useState('4');
  const [subjects, setSubjects] = useState<Subject[]>([
    { name: '', credits: 3, difficulty: 'Medium' }
  ]);
  const [weeklyHours, setWeeklyHours] = useState('25');
  const [interests, setInterests] = useState('');
  const [calendarEvents, setCalendarEvents] = useState('');

  const addSubject = () => {
    setSubjects([...subjects, { name: '', credits: 3, difficulty: 'Medium' }]);
  };

  const removeSubject = (index: number) => {
    setSubjects(subjects.filter((_, i) => i !== index));
  };

  const updateSubject = (index: number, field: string, value: any) => {
    const updated = [...subjects];
    (updated[index] as any)[field] = value;
    setSubjects(updated);
  };

  const handleAnalyze = async () => {
    setError(null);
    setLoading(true);

    try {
      // Validate inputs
      if (!semester || subjects.length === 0 || !weeklyHours) {
        throw new Error('Please fill in all required fields');
      }

      if (subjects.some(s => !s.name)) {
        throw new Error('All subjects must have a name');
      }

      const interestsList = interests
        .split(',')
        .map(i => i.trim())
        .filter(i => i.length > 0);

      console.log('📊 Sending semester data to backend...');

      const result = await callSemSenseAI({
        semesterNumber: parseInt(semester),
        studentName: userProfile?.full_name || 'Student',
        subjects,
        weeklyAvailableHours: parseInt(weeklyHours),
        studentInterests: interestsList.length > 0 ? interestsList : undefined,
        academicCalendar: calendarEvents
          ? { events: calendarEvents.split('\n').filter(e => e.trim()) }
          : undefined
      });

      console.log('✅ Analysis received:', result);
      setAnalysisResult(result as AnalysisResult);
      setStep('analysis');
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to generate semester plan';
      setError(message);
      console.error('💥 Error:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleSavePlan = async () => {
    if (!analysisResult) return;

    try {
      // TODO: Save to database
      console.log('💾 Saving semester plan...');
      alert('✅ Semester plan saved! You can sync it with your mentor.');
    } catch (err) {
      console.error('Error saving plan:', err);
      alert('Failed to save plan');
    }
  };

  const handleDownloadPlan = () => {
    if (!analysisResult) return;

    const content = `
SEMSENSE AI - SEMESTER PLAN
====================================

Student: ${analysisResult.data.studentName}
Semester: ${analysisResult.data.semesterNumber}
Generated: ${new Date(analysisResult.data.analysisTimestamp).toLocaleDateString()}
Weekly Hours Available: ${analysisResult.data.weeklyAvailableHours}

====================================
AI ANALYSIS & RECOMMENDATIONS
====================================

${analysisResult.data.aiAnalysis}

====================================
Generated by SemSense AI
Naalu Aksharam Padikk
====================================
    `;

    const element = document.createElement('a');
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(content));
    element.setAttribute('download', `SemPlan_Sem${analysisResult.data.semesterNumber}.txt`);
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="min-h-screen bg-neutral-900 text-white p-6">
      {/* Header */}
      <div className="max-w-6xl mx-auto mb-8">
        <button
          onClick={() => navigate('/dashboard')}
          className="flex items-center gap-2 text-gray-400 hover:text-gray-300 mb-6 transition"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Dashboard
        </button>

        {step === 'form' ? (
          <div>
            <div className="flex items-center gap-3 mb-2">
              <Brain className="w-8 h-8 text-purple-500" />
              <h1 className="text-4xl font-bold">SemSense AI</h1>
            </div>
            <p className="text-gray-400">Plan your semester wisely with AI-powered guidance</p>
          </div>
        ) : (
          <div>
            <h1 className="text-3xl font-bold mb-2">Your Semester Plan</h1>
            <p className="text-gray-400">
              Semester {analysisResult?.data.semesterNumber} • Generated {new Date(analysisResult?.data.analysisTimestamp || '').toLocaleDateString()}
            </p>
          </div>
        )}
      </div>

      <div className="max-w-6xl mx-auto">
        {error && (
          <Card className="bg-red-900/20 border-red-800 mb-6">
            <CardContent className="pt-6">
              <p className="text-red-300">❌ {error}</p>
            </CardContent>
          </Card>
        )}

        {step === 'form' ? (
          <div className="space-y-6">
            {/* Semester Setup Card */}
            <Card className="bg-neutral-900 border border-neutral-800">
              <CardHeader>
                <h2 className="text-xl font-bold text-white flex items-center gap-2">
                  <span className="w-8 h-8 rounded-full bg-purple-500/20 flex items-center justify-center text-purple-400">1</span>
                  Semester Setup
                </h2>
              </CardHeader>
              <CardContent className="space-y-6">
                {/* Basic Info */}
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm text-gray-400 mb-2">Semester Number *</label>
                    <Input
                      type="number"
                      value={semester}
                      onChange={e => setSemester(e.target.value)}
                      className="bg-neutral-800 border-neutral-700 text-white"
                      min="1"
                      max="8"
                    />
                  </div>
                  <div>
                    <label className="block text-sm text-gray-400 mb-2">Weekly Available Hours *</label>
                    <Input
                      type="number"
                      value={weeklyHours}
                      onChange={e => setWeeklyHours(e.target.value)}
                      className="bg-neutral-800 border-neutral-700 text-white"
                      min="1"
                      max="168"
                    />
                  </div>
                </div>

                {/* Subjects */}
                <div>
                  <label className="block text-sm text-gray-400 mb-3">Your Subjects *</label>
                  <div className="space-y-3">
                    {subjects.map((subject, idx) => (
                      <div key={idx} className="flex gap-3">
                        <Input
                          placeholder="Subject name (e.g., Data Structures)"
                          value={subject.name}
                          onChange={e => updateSubject(idx, 'name', e.target.value)}
                          className="flex-1 bg-neutral-800 border-neutral-700 text-white"
                        />
                        <Input
                          type="number"
                          placeholder="Credits"
                          value={subject.credits}
                          onChange={e => updateSubject(idx, 'credits', parseInt(e.target.value))}
                          className="w-20 bg-neutral-800 border-neutral-700 text-white"
                          min="1"
                          max="6"
                        />
                        <select
                          value={subject.difficulty}
                          onChange={e => updateSubject(idx, 'difficulty', e.target.value)}
                          className="px-3 bg-neutral-800 border border-neutral-700 text-white rounded-md text-sm"
                        >
                          <option>Easy</option>
                          <option>Medium</option>
                          <option>Hard</option>
                        </select>
                        {subjects.length > 1 && (
                          <Button
                            onClick={() => removeSubject(idx)}
                            variant="outline"
                            className="border-red-800 text-red-400"
                          >
                            Remove
                          </Button>
                        )}
                      </div>
                    ))}
                  </div>
                  <Button
                    onClick={addSubject}
                    variant="outline"
                    className="mt-3 border-purple-600 text-purple-400 hover:bg-purple-600/10"
                  >
                    + Add Subject
                  </Button>
                </div>

                {/* Interests */}
                <div>
                  <label className="block text-sm text-gray-400 mb-2">
                    Interests (comma-separated)
                  </label>
                  <Input
                    placeholder="e.g., Machine Learning, Web Development, Open Source"
                    value={interests}
                    onChange={e => setInterests(e.target.value)}
                    className="bg-neutral-800 border-neutral-700 text-white"
                  />
                  <p className="text-xs text-gray-500 mt-1">
                    Help AI suggest relevant projects and skills
                  </p>
                </div>

                {/* Calendar Events */}
                <div>
                  <label className="block text-sm text-gray-400 mb-2">
                    Academic Calendar Events (optional)
                  </label>
                  <Textarea
                    placeholder="e.g.,&#10;Mid Exams: March 15&#10;End Exams: May 20&#10;Holidays: Jan 26"
                    value={calendarEvents}
                    onChange={e => setCalendarEvents(e.target.value)}
                    className="bg-neutral-800 border-neutral-700 text-white text-sm"
                    rows={3}
                  />
                </div>
              </CardContent>
            </Card>

            {/* Action Buttons */}
            <div className="flex gap-4">
              <Button
                onClick={handleAnalyze}
                disabled={loading}
                className="flex-1 bg-purple-600 hover:bg-purple-700 text-white font-semibold py-6 text-lg"
              >
                {loading ? (
                  <>
                    <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                    Analyzing with AI...
                  </>
                ) : (
                  <>
                    <Brain className="w-5 h-5 mr-2" />
                    Generate My Semester Plan
                  </>
                )}
              </Button>
            </div>
          </div>
        ) : (
          /* Analysis Results */
          <div className="space-y-6">
            {/* Summary Card */}
            <Card className="bg-gradient-to-r from-purple-900/20 to-indigo-900/20 border border-purple-800/50">
              <CardContent className="pt-6">
                <div className="grid grid-cols-3 gap-4">
                  <div>
                    <p className="text-gray-400 text-sm">Semester</p>
                    <p className="text-2xl font-bold text-purple-400">
                      {analysisResult?.data.semesterNumber}
                    </p>
                  </div>
                  <div>
                    <p className="text-gray-400 text-sm">Subjects</p>
                    <p className="text-2xl font-bold text-indigo-400">
                      {analysisResult?.data.subjectsCount}
                    </p>
                  </div>
                  <div>
                    <p className="text-gray-400 text-sm">Weekly Hours</p>
                    <p className="text-2xl font-bold text-purple-400">
                      {analysisResult?.data.weeklyAvailableHours}h
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* AI Analysis */}
            <Card className="bg-neutral-900 border border-neutral-800">
              <CardHeader>
                <h2 className="text-xl font-bold text-white flex items-center gap-2">
                  <Brain className="w-5 h-5 text-purple-400" />
                  AI-Powered Semester Analysis
                </h2>
              </CardHeader>
              <CardContent>
                <div className="prose prose-invert max-w-none">
                  <div className="bg-neutral-800 p-6 rounded-lg whitespace-pre-wrap text-gray-300 text-sm leading-relaxed">
                    {analysisResult?.data.aiAnalysis}
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Action Buttons */}
            <div className="grid grid-cols-3 gap-4">
              <Button
                onClick={handleSavePlan}
                className="flex items-center justify-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white"
              >
                <Save className="w-4 h-4" />
                Save Plan
              </Button>
              <Button
                onClick={handleDownloadPlan}
                className="flex items-center justify-center gap-2 bg-neutral-800 hover:bg-neutral-700 text-white"
              >
                <Download className="w-4 h-4" />
                Download
              </Button>
              <Button
                onClick={() => {
                  alert('Share feature coming soon! Share with your mentor to get feedback.');
                }}
                className="flex items-center justify-center gap-2 bg-neutral-800 hover:bg-neutral-700 text-white"
              >
                <Share2 className="w-4 h-4" />
                Share with Mentor
              </Button>
            </div>

            {/* Quick Tips */}
            <Card className="bg-neutral-900 border border-neutral-800">
              <CardHeader>
                <h3 className="text-lg font-bold text-white">💡 How to Use This Plan</h3>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="flex gap-3">
                  <Badge className="bg-purple-600">1</Badge>
                  <p className="text-gray-300">Review the workload analysis to understand the semester difficulty</p>
                </div>
                <div className="flex gap-3">
                  <Badge className="bg-purple-600">2</Badge>
                  <p className="text-gray-300">Follow the weekly academic plan as a guideline for study intensity</p>
                </div>
                <div className="flex gap-3">
                  <Badge className="bg-purple-600">3</Badge>
                  <p className="text-gray-300">Save your plan and sync it with your mentor for personalized feedback</p>
                </div>
                <div className="flex gap-3">
                  <Badge className="bg-purple-600">4</Badge>
                  <p className="text-gray-300">Use project suggestions to build portfolio alongside academics</p>
                </div>
                <div className="flex gap-3">
                  <Badge className="bg-purple-600">5</Badge>
                  <p className="text-gray-300">Track your progress with study logs and adjust as needed</p>
                </div>
              </CardContent>
            </Card>

            {/* Back to Form */}
            <Button
              onClick={() => {
                setStep('form');
                setError(null);
              }}
              variant="outline"
              className="w-full border-neutral-700 text-gray-400 hover:text-gray-300"
            >
              ← Plan Another Semester
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}
